### ISSUE TITLE
New install fails to use RAM disk

### ISSUE THREAD

**Issue by johanberglin** [BeamCtrl/Airiana#17]
**Describe the bug**
I get RAM disk errors after installing and webserver does not start

**To Reproduce**
I have a PI zero W 1.1
I useed raspberry pi imager to put latest vanilla raspberry pi image on sdcard (both light and normal version tested)
updated so that it connected to wifi 
after initial boot via putty i ran these commands
sudo apt-get update 
sudo apt-get upgrade
sudo apt-get install git
git clone https://github.com/BeamCtrl/Airiana
cd Airiana
sudo python ./install.py

**Expected behavior**
Airiana starts properly

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by BeamCtrl** [comment]
Thank you for this, found a series of static paths that are not updated properly during install. Will update shortly.

**Comment by BeamCtrl** [comment]
pushed fixes, now the install script will update static paths to match during installation. from `690edfc`
