### ISSUE TITLE
Docker Container

### ISSUE THREAD

**Issue by Ontrackx** [BeamCtrl/Airiana#31]
Does anyone have this software nicly wrapped in a docker container (for use on a synolgy nas)

**Comment by BeamCtrl** [comment]
not that I know of, My guess it would not be to hard to get it up and running but it is not something I will put time into at this moment, You'd be very welcome to try and get a pull request up if you get it working. 
//Daniel

**Comment by BeamCtrl** [comment]
closed due to inactivity
